# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pytest --pylint src/
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: pytest --mypy src/
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        entry: pytest test/
        language: system
        pass_filenames: false
        always_run: true