[tool.poetry]
name = "Pyvalve"
version = "0.1.2"
description = "Asyncio python clamav client"
authors = ["Bradley Sacks <bradsacks99@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/bradsacks99/pyvalve"
documentation = "https://github.com/bradsacks99/pyvalve/blob/master/README.md"

[tool.poetry.dependencies]
python = "^3.8"
aiopath = "^0.5.12"
asyncinit = "^0.2.4"
aiofile = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-pylint = "^0.18.0"
pytest-mypy = "^0.9.1"
scriv = {extras = ["toml"], version = "^0.16.0"}
pre-commit = "^2.20.0"
pytest-asyncio = "^0.19.0"
sphinx-autodoc-typehints = "^1.19.2"
sphinx-markdown-builder = "^0.5.5"
Sphinx = "^5.1.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[package]
include = ["src/*.py"]

[scriv]
version = "literal: src/pyvalve/__init__.py: __version__"
format ="md"